name: Waka Readme

on:
  workflow_dispatch:
  schedule:
    # Runs at 06:00AM UTC Every Monday
    - cron: "0 6 * * Mon"

jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
